baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[params]
  author = "Md Hadiullah Akib" 
  description = "Cybersecurity notes, lab reports, and portfolio."

[taxonomies]
  tag = "tags"

summaryLength = 200
