baseURL = 'https://mdhadiullahakib.github.io/cyberfolio/'
locale = 'en-us'
title = 'My portfolio and documentation site'

[params]
  author = "Md Hadiullah Akib" 
  description = "Cybersecurity notes, lab reports, and portfolio."

[taxonomies]
  tag = "tags"

summaryLength = 200
